# Generated by Django 4.1.1 on 2023-02-09 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='post_date',
            field=models.DateField(default=datetime.date(2023, 2, 8)),
        ),
    ]
