# Generated by Django 4.1.1 on 2023-02-16 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paymentmodel_alter_item_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='item',
            name='post_date',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='credit_card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
