# Generated by Django 4.1.1 on 2023-02-18 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_profile_account_number_alter_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
