# Generated by Django 4.1.1 on 2023-02-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_post_date_order_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
